### PR TITLE
chore(ci) : setup test and lint workflows

### PR DESCRIPTION
**Pull request by mmorel-35**
Hi ! This PR defines golangci-lint and test workflows.
I have disable several linters because they needs to be fixed before being activated.

### CODE REVIEW

**Comment by bketelsen** [comment]
Thanks for this PR!
Do you want to compare and merge with #29 that I must have submitted just after yours? I think you added a few extra bits.

**Comment by mmorel-35** [comment]
Merge your pr first, I'll create a new one with the parts you didn't included

**Comment by bketelsen** [comment]
done

**Comment by mmorel-35** [comment]
Hi  @bketelsen, it's ready.
Just one question why using the vendor mod ?

**Comment by mmorel-35** [comment]
Friendly ping @bketelsen. When you have the time to review this 😊

**Review by bketelsen — APPROVED** [review]
Great Thank you!

**Pull request merged**
