### PR TITLE
Use new etcd modules

### PR DESCRIPTION
**Pull request by sagikazarmark**
This is a draft showing how the dependencies will look like, once the new etcd modules are released. This will resolve a lot of dependency issues in my opinion.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
PR updated to the latest alpha version.

**Comment by sagikazarmark** [comment]
I think this is ready for review. We might want to wait for the stable release, but as of yesterday etcd 3.5 is in feature freeze.

**Comment by vvakame** [comment]
@bketelsen I would be very happy if this PR was reviewed and a new release was made. 🌹

**Comment by andig** [comment]
Ping @bketelsen any opportunity to look at this pr?

**Comment by sagikazarmark** [comment]
Even if it gets merged, I don't think it should be released until etcd 3.5 is tagged as well.

**Comment by andig** [comment]
Imho it would still be nice to get this merged so people can start playing with it at master/main. At any rate a sign of maintainer interest would be appreciated.

**Comment by andig** [comment]
Should also fix https://github.com/bketelsen/crypt/issues/14

**Comment by sagikazarmark** [comment]
You can play with my fork using replace. I'll update the PR to rc.0 later today.

**Comment by bketelsen** [comment]
Merged but not tagged.  Let me know if this works and a release is warranted

**Comment by sagikazarmark** [comment]
Thanks @bketelsen ! I would wait with the release at least until the first RC (which should be out anytime). I'll keep sending PRs with the latest etcd version.

**Pull request merged**
